name: screws
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - absl-py=2.1.0=py310haa95532_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=py_0
  - blas=1.0=mkl
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotlicffi=1.0.9.2=py310h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py310h214f63a_0
  - cpuonly=2.0=0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py310haa95532_0
  - flatbuffers=24.3.25=h21716d4_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py310hdb0e946_0
  - freetype=2.13.3=h0620614_0
  - gast=0.6.0=pyhd3eb1b0_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=hac47afa_2
  - grpcio=1.71.0=py310hbb1fe6b_0
  - h5py=3.14.0=py310h6fc9867_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.11=py310haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libblas=3.9.0=26_win64_mkl
  - libboost=1.88.0=h3d2b97d_0
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=26_win64_mkl
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=26_win64_mkl
  - liblightgbm=4.6.0=cpu_h5d2ca61_6
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxgboost=2.0.3=cpu_h0f92c63_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - lightgbm=4.6.0=cpu_py_6
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.4.1=py310haa95532_0
  - markdown-it-py=4.0.0=py310haa95532_0
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib=3.10.6=py310haa95532_0
  - matplotlib-base=3.10.6=py310h43afe63_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - ml_dtypes=0.5.1=py310h094160a_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpi=1.0=msmpi
  - mpi4py=4.0.3=py310h827c3e9_0
  - mpmath=1.3.0=py310haa95532_0
  - msmpi=10.1.1=had4844c_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - namex=0.1.0=py310haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py310haa95532_0
  - numpy=2.0.1=py310h055cbcc_1
  - numpy-base=2.0.1=py310h65a83cf_1
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.14.1=py310h214f63a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h1637853_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=2.0.3=cpu_py310h09d19d8_0
  - pycparser=2.23=py310haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=6.9.1=py310h12ec796_0
  - pyqt6-sip=13.10.2=py310h630b2a1_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-flatbuffers=24.3.25=py310haa95532_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=27.1.0=py310h535538e_0
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - requests=2.32.5=py310haa95532_1
  - rich=14.2.0=py310haa95532_0
  - scikeras=0.13.0=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py310haa95532_0
  - sip=6.12.0=py310h706e071_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310h8f3aa81_1
  - sympy=1.14.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard=2.19.0=py310haa95532_0
  - tensorboard-data-server=0.7.0=py310haa95532_1
  - tensorflow-base=2.19.1=cpu_py310h4cf5749_0
  - termcolor=3.2.0=py310haa95532_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tomli=2.3.0=pyhcf101f3_0
  - torchaudio=2.5.1=py310_cpu
  - torchvision=0.20.1=py310_cpu
  - tornado=6.5.2=py310h29418f3_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py310h29418f3_0
  - urllib3=2.5.0=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - wrapt=1.17.0=py310h827c3e9_0
  - xgboost=2.0.3=cpu_py310h09d19d8_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - einops==0.8.1
      - etils==1.13.0
      - fsspec==2025.10.0
      - gdown==5.2.0
      - immutabledict==4.2.2
      - importlib-resources==6.5.2
      - kagglehub==0.3.13
      - keras==3.12.0
      - libclang==18.1.1
      - opencv-python==4.12.0.88
      - promise==2.3
      - protobuf==4.21.12
      - pyarrow==22.0.0
      - regex==2025.11.3
      - simple-parsing==0.1.7
      - soupsieve==2.8
      - tensorflow==2.20.0
      - tensorflow-datasets==4.9.9
      - tensorflow-io-gcs-filesystem==0.31.0
      - toml==0.10.2

